-- AlterTable
ALTER TABLE `Request` MODIFY `status` ENUM('PENDING', 'PENDING_BY_SP', 'ACCEPTED', 'DECLINED', 'CANCELED', 'COMING', 'IN_PROGRESS', 'FINISHED', 'INVOICED', 'PAID') NOT NULL DEFAULT 'PENDING_BY_SP';

-- AlterTable
ALTER TABLE `Service` MODIFY `status` ENUM('PENDING', 'PENDING_BY_SP', 'ACCEPTED', 'DECLINED', 'CANCELED', 'COMING', 'IN_PROGRESS', 'FINISHED', 'INVOICED', 'PAID') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `ServiceProvider` MODIFY `status` ENUM('PENDING', 'PENDING_BY_SP', 'ACCEPTED', 'DECLINED', 'CANCELED', 'COMING', 'IN_PROGRESS', 'FINISHED', 'INVOICED', 'PAID') NOT NULL DEFAULT 'PENDING';
