-- AlterTable
ALTER TABLE `Service` MODIFY `status` ENUM('PENDING', 'ACCEPTED', 'DECLINED') NOT NULL DEFAULT 'ACCEPTED';

-- AlterTable
ALTER TABLE `ServiceProvider` MODIFY `status` ENUM('PENDING', 'ACCEPTED', 'DECLINED') NOT NULL DEFAULT 'ACCEPTED';
