-- AlterTable
ALTER TABLE `Customer` MODIFY `role` ENUM('CUSTOMER', 'SERVICE_PROVIDER', 'WORKER', 'ADMIN') NOT NULL DEFAULT 'CUSTOMER';

-- AlterTable
ALTER TABLE `ServiceProvider` MODIFY `role` ENUM('CUSTOMER', 'SERVICE_PROVIDER', 'WORKER', 'ADMIN') NOT NULL DEFAULT 'SERVICE_PROVIDER';

-- CreateTable
CREATE TABLE `Admin` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(191) NOT NULL,
    `phoneNumber` VARCHAR(191) NOT NULL,
    `role` ENUM('CUSTOMER', 'SERVICE_PROVIDER', 'WORKER', 'ADMIN') NOT NULL DEFAULT 'ADMIN',

    UNIQUE INDEX `Admin_phoneNumber_key`(`phoneNumber`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
